export const getResultsRpa = (state) => state.rpa_result
export const getResultsRpaChart = (state) => state.rpa_resultChart
export const getResultsRpaSelected = (state) => state.rpa_result_selected
export const getBrowserRemote = (state) => state.rpa_browser_remote
export const getRpaUser = (state) => state.rpa_user
export const getRpaUserUnique = (state) => state.rpa_user_unique
export const getRpaUserAll = (state) => state.rpa_user_all
export const getRpaUserDelete = (state) => state.rpa_user_delete
export const getRpaEvents = (state) => state.rpa_events
export const getRpaBacklogProcessed = (state) => state.rpa_backlog_processed
export const getRpaTimerMedio = (state) => state.rpa_timer_medio_min