export const RPA_RESULT_SUCCESS = 'RPA_RESULT_SUCCESS'
export const RPA_RESULT_ERROR = 'RPA_RESULT_ERROR'

export const RPA_RESULT_SELECTED_SUCCESS = 'RPA_RESULT_SELECTED_SUCCESS'
export const RPA_RESULT_SELECTED_ERROR = 'RPA_RESULT_SELECTED_ERROR'

export const RPA_IMPORT_SUCCESS = 'RPA_IMPORT_SUCCESS'
export const RPA_IMPORT_ERROR = 'RPA_IMPORT_ERROR'

export const RPA_BROWSER_REMOTE_SUCCESS = 'RPA_RESULT_SUCCESS'
export const RPA_BROWSER_REMOTE_ERROR = 'RPA_RESULT_ERROR'

export const RPA_USER_SUCCESS = 'RPA_USER_SUCCESS'
export const RPA_USER_ERROR = 'RPA_USER_ERROR'

export const RPA_USER_DELETE_SUCCESS = 'RPA_USER_DELETE_SUCCESS'
export const RPA_USER_DELETE_ERROR = 'RPA_USER_DELETE_ERROR'

export const RPA_USER_ALL_SUCCESS = 'RPA_USER_ALL_SUCCESS'
export const RPA_USER_ALL_ERROR = 'RPA_USER_ALL_ERROR'

export const RPA_EVENTS_SUCCESS = 'RPA_EVENTS_SUCCESS'
export const RPA_EVENTS_ERROR = 'RPA_EVENTS_ERROR'