export const RPA_RESULT_SUCCESS = 'RPA_RESULT_SUCCESS'
export const RPA_RESULT_ERROR = 'RPA_RESULT_ERROR'
export const RPA_RESULT_SELECTED_SUCCESS = 'RPA_RESULT_SELECTED_SUCCESS'
export const RPA_RESULT_SELECTED_ERROR = 'RPA_RESULT_SELECTED_ERROR'